### ISSUE TITLE
Improve readme with FoxDot example

### ISSUE THREAD

**Issue by Vamoss** [feature-creature/FoxDot-to-P5js#1]
Hi,

first of all, thank you for this amazing project.

I just want to suggest you to add the foxdot example in the readme.

I think this is the missing code:
```py
Server.add_forward("localhost",12345)

p1 >> play("x ", amplify=0.25)
b1 >> jbass([2,4], oct=3, dur=4)

g2 >> growl([2,4,6], dur=1/6).every(3, 'reverse')
p2 >> play("(o,-),xx")
```

Cheers,
Carlos

**Comment by feature-creature** [comment]
Thanks for the suggestion, Carlos! I have updated the readme accordingly.
